# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    app.rsa_key_manager:
        class:    AppBundle\Service\RSAKeyManager
        arguments: []

    app.csvtoarray:
        class: AppBundle\Service\CSVToArray
        arguments: []
