# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    app.rsa_key_manager:
        class:    AppBundle\Service\RSAKeyManager
        arguments: []

    app.csvtoarray:
        class: AppBundle\Service\CSVToArray
        arguments: []

    app.user_manager:
        class:    AppBundle\Service\UserManager
        arguments:    ["@app.rsa_key_manager", "@doctrine.orm.entity_manager", "@fos_user.user_manager"]

    user.login_success_handler:
        class: UserBundle\Handler\AuthenticationSuccessHandler
        arguments: ["@router"]

    user.session_idle_handler:
        class: UserBundle\Handler\SessionIdleHandler
        arguments: ["@session", "@security.token_storage", "@router", %session_max_idle_time%]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
